<?php 
/**
* Configure ACF settings for use in the theme
*/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5967e8f99db82',
	'title' => 'Page Builder Template',
	'fields' => array (
		array (
			'key' => 'field_59b01860cc56a',
			'label' => 'How to use this page template:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'This page template is used to create long scrolling pages, multi column layouts, and more. Different sections can be added by clicking on the "+" icon. Drag and drop the sections to reorder them on your page.

Full help documentation can be found at <a href="https://stnsvn.com/help/paloma" target="_blank">https://stnsvn.com/help/paloma</a>.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_59af80e841f36',
			'label' => 'Page Title Display',
			'name' => 'page_title_display',
			'type' => 'true_false',
			'instructions' => 'Choose whether to display the page title or not.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Page title visible.',
			'ui_off_text' => 'Page title hidden',
		),
		array (
			'key' => 'field_5967e8f9a85d4',
			'label' => 'Content Sections',
			'name' => 'landing_content_sections',
			'type' => 'flexible_content',
			'instructions' => 'Click "Add Section" to begin adding content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'5621767e07a10' => array (
					'key' => '5621767e07a10',
					'name' => 'content_columns',
					'label' => 'Content Section',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5967ea767fed0',
							'label' => 'Title Text',
							'name' => 'column_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Enter section title text here.',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5967e8f9bba07',
							'label' => 'Number of Content Columns',
							'name' => 'number_of_content_columns',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								1 => '1',
								2 => '2',
								3 => '3',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
							'return_format' => 'value',
						),
						array (
							'key' => 'field_5967e8f9bba12',
							'label' => 'Column 1 Content',
							'name' => 'column_1_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5967e8f9bba1d',
							'label' => 'Column 2 Content',
							'name' => 'column_2_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5967e8f9bba07',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5967e8f9bba28',
							'label' => 'Column 3 Content',
							'name' => 'column_3_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5967e8f9bba07',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_599317e96ee68',
							'label' => 'Column 1 Width',
							'name' => 'column_1_width_2_column',
							'type' => 'number',
							'instructions' => 'Enter a % width for this column (default is 50).
Note: Column 2 width will be set automatically as the remainder.',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5967e8f9bba07',
										'operator' => '==',
										'value' => '2',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => 50,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 100,
							'step' => '',
						),
						array (
							'key' => 'field_599316956ee66',
							'label' => 'Column 1 Width',
							'name' => 'column_1_width_3_column',
							'type' => 'number',
							'instructions' => 'Enter a % width for this column (default is 33.3).
Note: Column 3 width will be set automatically as the remainder.',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5967e8f9bba07',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '33.3',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 50,
							'step' => '',
						),
						array (
							'key' => 'field_599316e36ee67',
							'label' => 'Column 2 Width',
							'name' => 'column_2_width',
							'type' => 'number',
							'instructions' => 'Enter a % width for this column (default is 33.3). 
Note: Column 3 width will be set automatically as the remainder.',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5967e8f9bba07',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '33.3',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 50,
							'step' => '',
						),
						array (
							'key' => 'field_5967ea8b7fed1',
							'label' => 'Background Color',
							'name' => 'column_bg',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_5967eaa57fed2',
							'label' => 'Background Image',
							'name' => 'column_bg_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5967eac57fed3',
							'label' => 'Text Color',
							'name' => 'column_text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_59684e0ed8e23',
							'label' => 'Button Text',
							'name' => 'column_button_text',
							'type' => 'text',
							'instructions' => 'Leave blank to not display a button.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59684e33d8e24',
							'label' => 'Button URL',
							'name' => 'column_button_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_59685a2ec0ae7',
							'label' => 'Content Width',
							'name' => 'column_content_width',
							'type' => 'number',
							'instructions' => 'Enter in the maximum width (in px) for the content in this section.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5967f223d4055' => array (
					'key' => '5967f223d4055',
					'name' => 'landing_slider',
					'label' => 'Photo Slider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599e004eb7d3a',
							'label' => 'Slider Title',
							'name' => 'slider_title',
							'type' => 'text',
							'instructions' => 'Optional - the slider title does not display anywhere but is used as the section id.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5967f22bd4056',
							'label' => 'Slide Image',
							'name' => 'landing_slide',
							'type' => 'repeater',
							'instructions' => 'Please note: minimum image dimensions: 1875 x 750px. All images must be larger than 1875 x 750px and will be cropped to fit.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Slide',
							'sub_fields' => array (
								array (
									'key' => 'field_5967f31a836ee',
									'label' => 'Slide Image',
									'name' => 'slide_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'5991f66dd874f' => array (
					'key' => '5991f66dd874f',
					'name' => 'testimonial_slider',
					'label' => 'Testimonial Slider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5991f6d8d8754',
							'label' => 'Title Text',
							'name' => 'testimonial_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5991f66dd8750',
							'label' => 'Testimonial Slide',
							'name' => 'testimonial_slide',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Testimonial',
							'sub_fields' => array (
								array (
									'key' => 'field_5991f66dd8752',
									'label' => 'Testimonial Content',
									'name' => 'testimonial_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array (
									'key' => 'field_5991f714d8755',
									'label' => 'Testimonial Attribution',
									'name' => 'testimonial_attribution',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array (
							'key' => 'field_5991f699d8753',
							'label' => 'Background Image',
							'name' => 'testimonial_bg_image',
							'type' => 'image',
							'instructions' => 'Upload your section background image here.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5968104e4f513' => array (
					'key' => '5968104e4f513',
					'name' => 'masonry_grid',
					'label' => 'Masonry Grid',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_598de48cf06a1',
							'label' => 'Title Text',
							'name' => 'masonry_title_text',
							'type' => 'text',
							'instructions' => 'Enter an optional section title here.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59684db2d8e22',
							'label' => 'Intro Content',
							'name' => 'masonry_content',
							'type' => 'wysiwyg',
							'instructions' => 'Enter any content to display before the masonry feed.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_596810594f514',
							'label' => 'Masonry Items',
							'name' => 'masonry_items',
							'type' => 'relationship',
							'instructions' => 'Select items to include in the masonry grid. Ensure you have set featured images for each post/page to display in the grid.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => array (
							),
							'filters' => array (
								0 => 'search',
								1 => 'post_type',
								2 => 'taxonomy',
							),
							'elements' => array (
								0 => 'featured_image',
							),
							'min' => '',
							'max' => '',
							'return_format' => 'object',
						),
						array (
							'key' => 'field_599209512f2d6',
							'label' => 'Title Display Style',
							'name' => 'masonry_title_style',
							'type' => 'select',
							'instructions' => 'Select how your titles will display.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'visible' => 'Visible',
								'hidden' => 'Hidden',
								'hover' => 'Display on hover',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5991d92cabf77',
							'label' => 'Background Color',
							'name' => 'masonry_bg',
							'type' => 'color_picker',
							'instructions' => 'Select an optional section background color here.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5968166c16e55' => array (
					'key' => '5968166c16e55',
					'name' => 'latest_posts',
					'label' => 'Latest Posts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_598de54a4d7e3',
							'label' => 'Title Text',
							'name' => 'latest_title',
							'type' => 'text',
							'instructions' => 'Enter an optional section title here.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59685b89524cd',
							'label' => 'Content Before Posts',
							'name' => 'latest_content',
							'type' => 'wysiwyg',
							'instructions' => 'Enter any content to display before your latest posts.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5968167916e56',
							'label' => 'Number of Posts',
							'name' => 'number_of_posts',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => 1,
						),
						array (
							'key' => 'field_59685dba44a92',
							'label' => 'Content After Posts',
							'name' => 'content_after_posts',
							'type' => 'wysiwyg',
							'instructions' => 'Enter any content to display after your latest posts.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_596816c716e57',
							'label' => 'Category Filter',
							'name' => 'latest_categories',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'checkbox',
							'allow_null' => 0,
							'add_term' => 1,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array (
							'key' => 'field_596d3ed9eca75',
							'label' => 'Background Color',
							'name' => 'latest_background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#FBF9F5',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-builder.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56a183b99291e',
	'title' => 'Select Displayed Category',
	'fields' => array (
		array (
			'key' => 'field_56a183b9abf78',
			'label' => 'Select Displayed Category',
			'name' => 'displayed_category',
			'type' => 'taxonomy',
			'instructions' => 'Select which category is displayed above the title of the post.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'allow_null' => 1,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56259c4ab8fa7',
	'title' => 'Display Post in Slider',
	'fields' => array (
		array (
			'key' => 'field_56259c4abc156',
			'label' => '',
			'name' => 'display_post_in_slider',
			'type' => 'true_false',
			'instructions' => 'Check this box to display the current post in the latest posts slider (if enabled)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_598940e0dd4bb',
			'label' => 'Slide Order',
			'name' => 'slide_order',
			'type' => 'number',
			'instructions' => 'Enter the slide order here - lower numbered slides are displayed first.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_598940f7dd4bc',
			'label' => 'Slider Image',
			'name' => 'slider_image',
			'type' => 'image',
			'instructions' => 'Upload an alternate image to use in the slider. If no image uploaded, the default featured image will display.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_574f4c2b487a8',
	'title' => 'Author Bio Info',
	'fields' => array (
		array (
			'key' => 'field_574f4c31dd9b3',
			'label' => 'Author Photo',
			'name' => 'author_photo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_574f4d1999a43',
			'label' => 'Author Website',
			'name' => 'author_website',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f4d2b80e92',
			'label' => 'Author Facebook',
			'name' => 'author_facebook',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f4d3680e93',
			'label' => 'Author Twitter',
			'name' => 'author_twitter',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f4d3d80e94',
			'label' => 'Author Instagram',
			'name' => 'author_instagram',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f4d4380e95',
			'label' => 'Author Pinterest',
			'name' => 'author_pinterest',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'edit',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;